=== aga-mn/XML/wykaz.xsd
<?xml version="1.0" encoding="ISO-8859-2"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

	<xsd:complexType name="adres">
		<xsd:sequence>
			<xsd:element name="kod-poczt">
				<xsd:simpleType>
					<xsd:restriction base="xsd:string">
						<xsd:pattern value="\d{2}-\d{3}"/>
					</xsd:restriction>
				</xsd:simpleType>
			</xsd:element>
			<xsd:element name="miasto" type="xsd:string"/>
			<xsd:element name="ulica" type="xsd:string"/>
			<xsd:element name="numer" type="xsd:positiveInteger"/>
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="osoba">
		<xsd:sequence>
			<xsd:element name="imie" type="xsd:string" />
			<xsd:element name="nazwisko" type="xsd:string" />
			<xsd:element name="stanowisko" type="xsd:string" minOccurs="0"/>
		</xsd:sequence>
	</xsd:complexType>
	
	<xsd:element name="wykaz">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="miejsce" type="xsd:string"/>
				<xsd:element name="data" type="xsd:date"/>
				<xsd:element name="wspolnota">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="nazwa" type="xsd:string"/>
							<xsd:element name="adres" type="adres"/>
							<xsd:element name="rodzaj" type="xsd:string"/>
							<xsd:element name="inne" type="xsd:string"/>
							<xsd:element name="administrator" type="xsd:string"/>
							<xsd:element name="email" type="xsd:string"/>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="zdjecie" type="xsd:string" /> 
				<xsd:element name="wykaz-lokali">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="lokal" maxOccurs="unbounded" >
								<xsd:complexType>
									<xsd:sequence>
										<xsd:element name="numer-lokalu" type="xsd:integer"/>
										<xsd:element name="wlasciciel" type="osoba"/>
										<xsd:element name="dlug" type="xsd:decimal"/>
									</xsd:sequence>
								</xsd:complexType>
							</xsd:element>
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="sporzadzajacy" type="osoba"/>
				<xsd:element name="zlecajacy" type="osoba"/>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	
</xsd:schema>

=== aga-mn/XML/wykaz.xml
<?xml version="1.0" encoding="ISO-8859-2"?>
<?xml-stylesheet type="text/xsl" href="wykaz.xsl"?> 
<wykaz xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="wykaz.xsd">

<miejsce>Grodzisk Maz.</miejsce>
<data>2004-03-10</data>
<wspolnota>
<nazwa>Grunwaldzka</nazwa>
<adres>
<kod-poczt>05-825</kod-poczt>
<miasto>Grodzisk Maz.</miasto>
<ulica>Grunwaldzka</ulica>
<numer>7</numer>
</adres>
<rodzaj>blok mieszkalny</rodzaj>
<inne>brak</inne>
<administrator>Zarz¹d Budynków Komunalnych</administrator>
</wspolnota>
<zdjecie>IMG_0329.JPG</zdjecie>

<wykaz-lokali>
<lokal>
<numer-lokalu>3</numer-lokalu>
<wlasciciel> 
<imie>Jan</imie>
<nazwisko>M³oceñ</nazwisko>
</wlasciciel>
<dlug>245</dlug>
</lokal>

<lokal>
<numer-lokalu>7</numer-lokalu>
<wlasciciel> 
<imie>Kamila</imie>
<nazwisko>Mirko</nazwisko>
</wlasciciel>
<dlug>124.12</dlug>
</lokal>

<lokal>
<numer-lokalu>9</numer-lokalu>
<wlasciciel> 
<imie>Marian</imie>
<nazwisko>Kowal</nazwisko>
</wlasciciel>
<dlug>156.66</dlug>
</lokal>

</wykaz-lokali>

<sporzadzajacy>
<imie>Janina</imie>
<nazwisko>Kwiecien</nazwisko>
<stanowisko>Kierownik Dzia³u Czynszów</stanowisko>
</sporzadzajacy>

<zlecajacy>
<imie>Marian</imie>
<nazwisko>Biernacki</nazwisko>
<stanowisko>Dyrektor Zarz¹du Budynków Komunalnych</stanowisko>
</zlecajacy>
</wykaz>
